apiVersion: v2
name: steadybit-extension-datadog
description: Steadybit Kubernetes extension Helm chart for Datadog.
version: 1.5.19
appVersion: v1.8.15
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: daniel.reuter@steadybit.com
    name: reuda
sources:
  - https://github.com/steadybit/extension-datadog
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: Steadybit website
      url: https://www.steadybit.com
    - name: Steadybit reliability hub
      url: https://hub.steadybit.com
dependencies:
  - name: extensionlib
    version: ^1.4.4
    repository: https://steadybit.github.io/helm-charts
